server:
  port: 9990

spring:
  boot:
    admin:      
      turbine:
        clusters: default
        location: monitor-service
  security:
      user:
        name: admin
        password: 123456


eureka:
  instance:
    metadata-map:
      user.name: "client"
      user.password: "client"

logging:
  file: "logs/admin-service-pro.log"

