server:
  port: 9998

spring:
  boot:
    admin:      
      turbine:
        clusters: default
        location: monitor-service
  security:
      user:
        name: admin
        password: 123456


eureka:
  instance:
      metadata-map:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}

logging:
  file: "logs/admin-service-pro.log"

